name: Helm Deployer
description: Helm wrapper intended for use with github.com/bcgov-nr/quickstart-openshift
branding:
  icon: package
  color: blue

inputs:
  ### Required
  release:
    description: Deployment release; usually PR number, test or prod
    required: true
    type: string
  namespace:
    description: OpenShift or Kubernetes namespace (e.g. abc123-dev)
    required: true
  server:
    description: OpenShift or Kubernetes server (e.g. https://api.silver.devops.gov.bc.ca:6443)
    required: true
  token:
    description: OpenShift or Kubernetes access token
    required: true

  ### Typical / recommended
  environment:
    description: Environment name; omit for PRs
    required: false
    type: string
  params:
    description: 'Extra parameters to pass to helm upgrade'
    default: ''
    required: false
    type: string
  triggers:
    description: Paths used to trigger a build; e.g. ('./backend/' './frontend/)
    required: false
    type: string

  ### Usually a bad idea / not recommended
  branch:
    description: Optionally, specify a different branch to clone
    default: ""
  diff_branch:
    description: Branch to diff against, picks up default if omitted
    default: "${{ github.event.repository.default_branch }}"
  directory:
    description: 'Chart directory'
    default: 'charts'
    required: false
    type: string
  repository:
    description: Optionally, specify a different repo to clone
    default: "${{ github.repository }}"
  values:
    description: 'Values file'
    default: 'values.yaml'
    required: false
    type: string

outputs:
  triggered:
    description: 'Has a deployment has been triggered?'
    value: ${{ jobs.deploys.outputs.triggered }}

runs:
  using: composite
  steps:
    # Clone, for charts
    - uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.branch }}

    # Process variables and inputs
    - id: vars
      shell: bash
      run: |
        # Expand for inputs and variables

        # Bug mitigation - OpenShift/Kubernetes hates images with capitals in org/repo names
        REPO=${{ inputs.repository }}
        if [[ $REPO != ${REPO,,} ]]; then
          echo -e "An OpenShift bug prevents capital letters in repo names.\n"
          echo -e "Please handle that using the `repository` parameter.\n"
          exit 1
        fi

        # Triggers
        TRIGGERS=${{ inputs.triggers }}
        if [ -z "${TRIGGERS}" ]; then
          echo "Triggers omitted, deployment required"
          echo "triggered=true" >> $GITHUB_OUTPUT
          exit 0
        else
          echo "Processing triggers"
          git fetch origin "${{ inputs.diff_branch }}"
          while read -r check; do
            for t in "${TRIGGERS[@]}"; do
              if [[ "${check}" =~ "${t}" ]]; then
                  echo -e "Triggered: ${t}\n --> ${check}"
                  echo "triggered=true" >> $GITHUB_OUTPUT
                  exit 0
              fi
            done
          done < <(git diff origin/"${{ inputs.diff_branch }}" --name-only)
        fi
        echo "Triggers not matched, deployment skipped"

    - if: steps.vars.outputs.triggered
      shell: bash
      run: |
        # Login to OpenShift/Kubernetes (NOTE: project command is a safeguard)
        oc login --token=${{ inputs.token }} --server=${{ inputs.server }}
        oc project ${{ inputs.namespace }}

    - if: steps.vars.outputs.triggered
      shell: bash
      run: |
        helm ${{ inputs.command }} ${{ inputs.release }} ${{ inputs.directory }} ${{ inputs.parameters }} \
          | sed '/^kind: Secret/,/^---/{//!d}' | sed '/^kind: Secret/ s/$/ \n  <REDACTED>/'

    # Action repo needs to be present for cleanup/tests
    - name: Checkout to make sure action.yml is present (tests)
      if: ${{ github.repository }} != ${{ inputs.repository }}
      uses: actions/checkout@v3
